theme: jekyll-theme-midnight
# Change the color of the page header
midnight:
  header_color: "#232545"

# Add a description to the site metadata
description: "My awesome Midnight-themed website"

# Enable syntax highlighting for code blocks
highlighter: rouge
